# fly.toml app configuration file generated for acefc-api on 2024-05-07T17:32:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'acefc-api'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="acefc-data"
  destination="/acefc-data"
